name: Build Binaries

on:
  push:
    branches: ["**"]
    tags: ["**"]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        go-version: ["1.21"]

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Build (Windows)
        if: runner.os == 'Windows'
        run: go build -v -o bulker.exe .

      - name: Build (Unix)
        if: runner.os != 'Windows'
        run: go build -v -o bulker .

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: bulker-${{ runner.os }}
          path: |
            bulker* 