name: Build and Release

on:
  push:
    branches: ["**"]
    tags: ["**"]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        go-version: ["1.21"]

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Build (Windows)
        if: runner.os == 'Windows'
        run: go build -v -o bulker.exe .

      - name: Build (Unix)
        if: runner.os != 'Windows'
        run: go build -v -o bulker .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: bulker-${{ runner.os }}
          path: |
            bulker*
          retention-days: 1

  release:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release and Upload Binaries
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/bulker-ubuntu-latest/bulker
            artifacts/bulker-windows-latest/bulker.exe 